blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:blog_id>', views.detail, name='detail'),
]

photoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class Blog(models.Model):
    title = models.CharField(blank=False, null=False, max_length=100)
    content = models.TextField(blank=True)
    image = models.ImageField(upload_to='image/', blank=True)
    # image = CloudinaryField('image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
from django.http import HttpResponseServerError
from django.views.decorators.csrf import requires_csrf_token
from django.shortcuts import render
from .models import Blog


def index(request):
    blogs = Blog.objects.order_by('-created_at')
    return render(request, 'blog/index.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

blog/templates/blog/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Page Index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{% static 'detail.css' %}"
    />
    <script src='{% static "detail.js" %}'></script>
  </head>
  <body>
    <h1>{{blog.title}}</h1>
    <h8>updated {{blog.updated_at}}</h8>
    <hr />
    <div>
      <img src="{{blog.image.url}}" alt="{{blog.content}}" width="80%" />
    </div>
    <p>{{blog.content}}</p>
    <hr />
    <a href='{% url 'blog:index'%}'>トップに戻る</a>
  </body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Page Index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{% static 'index.css' %}"
    />
    <script src='{% static "index.js" %}'></script>
  </head>
  <body>
    <h1>Khayi's Photo Library</h1>
    <p>記事一覧</p>
    <hr />
    {% for blog in blogs %}
    <div>
      <h3>{{blog.title}}</h3>
      <a href="{% url 'blog:detail' blog.id %}" target="_blank"
        ><img src="{{blog.image.url}}" alt="{{blog.content}}" width="80%"
      /></a>
    </div>
    <hr />
    {% endfor %}
  </body>
</html>